name: xnn
channels:
  - defaults
dependencies:
  - python=3.10.9
  - pip=23.0.1
  - pip:
      - pandas==1.5.2
      - numpy==1.24.1
      - pylint==2.15.0
      - pytest-cov==4.0.0
      - scikit-learn==1.2.2
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - matplotlib==3.7.1
      - mlflow==2.2.2
      - tensorflow==2.12.0
      - tensorflow==2.12.0
      - keras==2.12.0
      - pillow==9.4.0
      - pyarrow==11.0.0
      - streamlit==1.21.0

