files:
  data_dir: "C:/Users/angus/OneDrive/Desktop/AISG/Explainable-Neural-Networks/data/data"

model:
  model_params:
    dropout: 0.2
    optimizer: "adam"
    loss_function: "binary_crossentropy"

  model_architecture_params:
    n_layers: 3
    n_nodes: 8

  rescale_params:
    img_height: 224
    img_width: 224

  data_augmentation:
    random_flip: "horizontal"
    random_rotation: 0.2

  metrics:
    - 'accuracy'
    - 'Precision'
    - 'Recall'
    - 'AUC'

training_params:
  validation_split: 0.2
  batch_size: 100
  n_epochs: 10

mlflow:
  artifact_name: 'baseline-model'
  tracking_uri: "http://127.0.0.1:5000"
  experiment_name: "Baseline model"
  description: 'Training baseline model'
  model_name: finalized_model
  model_save_dir: ""
  tags:
    model-architecture: ''




