files:
  data_dir: "C:/Users/angus/OneDrive/Desktop/AISG/Explainable-Neural-Networks/data/data"



model:
  compile_params:
    loss_function: "categorical_crossentropy"
    learning_rate: 0.00001

  model_params:
    model_architecture_params:
      n_nodes: 15
      dropout: 0.2

    rescale_params:
      img_height: 224
      img_width: 224

    data_augmentation:
      random_flip: "horizontal_and_vertical"
      random_rotation: 0.4    

  training_params:
    validation_split: 0.2
    batch_size: 300
    n_epochs: 1

metrics:
  - 'accuracy'
  - 'Precision'
  - 'Recall'
  - 'AUC'

mlflow:
  artifact_name: 'baseline-model'
  experiment_name: "Fine tuned model"
  run_name: "Fine tuning"
  description: 'Fine tuning baseline model'
  model_name: finalized_model
  model_save_dir: ""
  tags:
    model-architecture: ''

fine_tuning:
  retrieve_params:
    run_id: "140308137141938706"
    model_uri: "cab1e769583c4ce9a4a54141e0d79f57"
    model_name: "finalized_model"
    destination_path: "./models"
  fine_tune_at: 145




